### ISSUE TITLE
Would it be possible to integrate OSC messaging features to it?

### ISSUE THREAD

**Issue by JunguGuo** [ideum/Touchless.Design-SDK#1]
So that it also allows guests to use their mobile phone as a remote control to interact with the software.

**Comment by kyleIdeum** [comment]
This is a very interesting idea and is certainly possible to implement - something we'll consider moving forward. That being said, I would like to get more information from you @JunguGuo about this idea. How do you see this working in practice? One of the biggest challenges in public spaces would be swapping between mobile devices. Is this scenario encompassed by your use case?
